# .github/workflows/sanity-check.yml
name: PR Sanity Check

on: pull_request
  workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Packages
        run: |
          npm install

      - name: Lint
        run: |
          npm run lint

      - name: Test
        run: |
          npm run test
